package com.platform.recruitment.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    COMPANY_NOT_VERIFIED,
    DUPLICATE_APPLICATION,
    INVALID_FILE,
    FILE_SIZE_EXCEEDED,
    EMAIL_NOT_VERIFIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    RATE_LIMIT_EXCEEDED,
    EMAIL_ALREADY_EXISTS,
    JOB_LEASE_LOST,
    FILE_STORAGE_FAILED,
    CV_TEXT_EXTRACTION_FAILED,
    CV_STRUCTURING_FAILED,
    CV_PROCESSING_FAILED,
    SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR
}
